build:
    environment:
        php:
            version: 7.0.1-dev
            ini:
                'date.timezone': 'UTC'
    tests:
        override:
            -
                command: phpunit --coverage-clover=my-coverage-file
                coverage:
                    file: my-coverage-file
                    format: php-clover