language: php

php:
  - 7.0

matrix:
  fast_finish: true

sudo: false

before_install:
    - composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-source --dev

#before_script:
#    - travis_retry composer self-update
#    - travis_retry composer install --no-interaction --prefer-source --dev

script:
    - phpunit --configuration phpunit.xml.dist --verbose
#    - phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover